package:
  name: aws-cli
  version: 1.27.136
  epoch: 0
  description: "Universal Command Line Interface for Amazon Web Services"
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - python3
      - py3-setuptools
      - py3-yaml
      - py3-botocore
      - py3-docutils
      - py3-jmespath
      - py3-rsa
      - py3-s3transfer
      - py3-colorama
      - groff
environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - python3
      - python3-dev
      - py3-setuptools
pipeline:
  - uses: fetch
    with:
      uri: https://github.com/aws/aws-cli/archive/${{package.version}}.tar.gz
      expected-sha256: 8fc21d2c27a60e5bcb4b97a3c3317247cddc98cec81a79f06ab23decf53ed54c
  - runs: |
      python3 setup.py build
  - runs: |
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}"
  - uses: strip
update:
  enabled: true
  github:
    identifier: aws/aws-cli
    use-tag: true
    tag-filter: "1.27"
